name:                geoip-redis
version:             0.1.0.0
github:              "Reykudo/geoip-redis"
license:             BSD3
author:              "Reykudo"
maintainer:          "example@example.com"
copyright:           "2022 Reykudo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Reykudo/geoip-redis#readme>

dependencies:
- base >= 4.7 && < 5
- conduit
- csv-conduit
- hedis
- mtl
- transformers
- bytestring
- text
- ip
- data-default
- vector
- ordered-containers
- optparse-applicative
- store
- pretty-simple 
- async
- unordered-containers
- linear-base
- containers

library:
  source-dirs: src

executables:
  geoip-redis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - geoip-redis

tests:
  geoip-redis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geoip-redis
